language: go
go:
  - 1.8.x
  - master
install:
  - go get -t github.com/FreifunkBremen/yanic/...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - ./.test-coverage
  - go install github.com/FreifunkBremen/yanic
